### ISSUE TITLE
arpeggio not working at all

### ISSUE THREAD

**Issue by shoumo2021** [PDBeurope/arpeggio#13]
Hello - just cannot get arpeggio to work, and would much appreciate some help! Thanks Shoumo
Installation as follows:
conda create -n arpeggio-env python=3.7 anaconda
conda activate arpeggio-env

In the arpeggio environment:
conda install -c openbabel openbabel
pip install git+https://github.com/PDBeurope/arpeggio.git@master#egg=arpeggio

openbabel  2.4.1
Python 3.7.13

(arpeggio-env) shoumo@Shoumos-MacBook-Pro pdb % arpeggio 1esr.pdb
INFO//10:24:54.943//Program begin.
WARNING//10:24:54.943//No selection was perceived. Defaults into full structure!!
DEBUG//10:24:54.956//Loaded PDB structure (BioPython)
DEBUG//10:24:55.523//Loaded PDB structure (OpenBabel)
ERROR//10:24:55.524//An OpenBabel atom could not be matched to a BioPython counterpart.
Traceback (most recent call last):
  File "/Users/shoumo/opt/anaconda3/envs/arpeggio-env/lib/python3.7/site-packages/arpeggio/core/interactions.py", line 1995, in _establish_structure_mappping
    biopython_atom = serial_to_bio[serial]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shoumo/opt/anaconda3/envs/arpeggio-env/bin/arpeggio", line 8, in <module>
    sys.exit(main())
  File "/Users/shoumo/opt/anaconda3/envs/arpeggio-env/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 79, in main
    run_arpeggio(args)
  File "/Users/shoumo/opt/anaconda3/envs/arpeggio-env/lib/python3.7/site-packages/arpeggio/scripts/process_protein_cli.py", line 89, in run_arpeggio
    i_complex = InteractionComplex(args.filename, args.vdw_comp, args.interacting, args.ph)
  File "/Users/shoumo/opt/anaconda3/envs/arpeggio-env/lib/python3.7/site-packages/arpeggio/core/interactions.py", line 92, in __init__
    self._establish_structure_mappping()
  File "/Users/shoumo/opt/anaconda3/envs/arpeggio-env/lib/python3.7/site-packages/arpeggio/core/interactions.py", line 1998, in _establish_structure_mappping
    raise OBBioMatchError(serial)
arpeggio.core.exceptions.OBBioMatchError: 0

**Comment by roshkjr** [comment]
arpeggio supports only structures in mmCIF format. PDB format is not supported
