### ISSUE TITLE
Arpeggio not working for 5rfa preferred assembly

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [PDBeurope/arpeggio#20]
I have downloaded the preferred assembly of 5rfa from here: https://www.ebi.ac.uk/pdbe/static/entry/download/5rfa-assembly-1.cif.gz, unzipped it and ran Arpeggio like so: `pdbe-arpeggio 5rfa-assembly-1.cif -s RESNAME:JGY`. The program crashes after loading the MMCIF structure with Openbabel with the following error:
```
Traceback (most recent call last):
  File "~/envs/arpeggio-env/bin/pdbe-arpeggio", line 8, in <module>
    sys.exit(main())
  File "~/envs/arpeggio-env/lib/python3.9/site-packages/arpeggio/scripts/process_protein_cli.py", line 150, in main
    run_arpeggio(args)
  File "~/envs/arpeggio-env/lib/python3.9/site-packages/arpeggio/scripts/process_protein_cli.py", line 159, in run_arpeggio
    i_complex = InteractionComplex(
  File "~/envs/arpeggio-env/lib/python3.9/site-packages/arpeggio/core/interactions.py", line 70, in __init__
    self.component_types = protein_reader.get_component_types(filename)
  File "~/envs/arpeggio-env/lib/python3.9/site-packages/arpeggio/core/protein_reader.py", line 437, in get_component_types
    raise ValueError('Missing _chem_comp. category in mmcif')
ValueError: Missing _chem_comp. category in mmcif
```

Any suggestions? Thanks!

**Comment by JavierSanchez-Utges** [comment]
I realised that the _chem_comp. category which is on the ASYM unit CIF is not in the BIO unit CIF. After commenting those code lines, it worked. However, the table missed the type of the residues, e.g., peptide, nucleic acid, non-polymer, etc.
